[application]

[web.app]

# HTML title tag content
title = "Portfolio"
hydrate = false      # Enable if using SSR/interactivity
platform = "web" # Explicitly set platform

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []


[bundle]
icon = ["assets/favicon.ico"]